[package]
name = "map"
version = "0.1.0"
edition = "2024"

[dependencies]
std_utils.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_yaml.workspace = true
